name: Mobile-Wallet CI[Master/Dev]

on:
  pull_request:
  push:
    branches:
      - 'dev'
      - 'master'
      - 'payment_hub'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Set up JDK
      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

        # Install NDK
      #- name: Install NDK
      # run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

        # Update Gradle Permission
      - name: Change gradlew Permission
        run: chmod +x gradlew

        # Build App
      - name: Build with Gradle
        run: ./gradlew assemble

        # Upload Built APK
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: mobile-wallet
          path: mifospay/build/outputs/apk/debug/

  lintCheck:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run lint on all modules
        run: ./gradlew runLintOnAllModules

      # Upload lint reports for all modules
      - name: Upload Static Analysis Reports
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: Static Analysis Reports
          path: |
            **/build/reports/lint-results*.html
            **/build/reports/lint-results*.xml
  

  pmd:
    name: PMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: PMD Check[Core]
        run: ./gradlew core:pmd

      - name: Upload PMD Report[Core]
        uses: actions/upload-artifact@v3.1.3
        if: failure()
        with:
          name: PMD Report[Core]
          path: core/build/reports/

      - uses: actions/checkout@v4
      - name: PMD Check[MifosPay]
        run: ./gradlew mifospay:pmd

      - name: Upload PMD Report[MifosPay]
        uses: actions/upload-artifact@v3.1.3
        if: failure()
        with:
          name: PMD Report[MifosPay]
          path: mifospay/build/reports/

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkstyle[Core]
        run: ./gradlew core:checkstyle

      - name: Upload Checkstyle Report[Core]
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: Checkstyle Report[Core]
          path: core/build/reports/

      - uses: actions/checkout@v2
      - name: Checkstyle[MifosPay]
        run: ./gradlew mifospay:checkstyle

      - name: Upload Checkstyle Report[MifosPay]
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: Checkstyle Report[MifosPay]
          path: mifospay/build/reports/
